### ISSUE TITLE
fliter、排序无效，以及鼠标悬停显示有误

### ISSUE THREAD

**Issue by Lenserf** [yudachi/plugin-ship-info#3]
Poi 版本 2.0.1，系统 OS X 10.10.3
如图所示：
![截图](http://ww2.sinaimg.cn/large/eb7f99fcgw1etd90rlqm1j20pw0l60ww.jpg)
fliter 无效，排序无效，以及鼠标悬停显示有误

**Comment by myzWILLmake** [comment]
Git里目前fixed
将会在下回poi更新中修复
